{{- range .Values.tenants }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    {{- include "multi-tenant-saas.labels" $ | nindent 4 }}
    tenant: {{ .id }}
---
{{- end }}
