apiVersion: v1
kind: Secret
metadata:
  name: tenant-c-secrets
  namespace: tenant-c
  labels:
    app: multi-tenant-saas
    tenant: tenant-c
type: Opaque
data:
  CONFIG_DB_PASSWORD: Y0hBTkdFX01F              # CHANGE_ME
  DB_PASSWORD:        Y0hBTkdFX01F              # CHANGE_ME
  DB_USER:            dGVuYW50X2NfdXNlcg==      # tenant_c_user
  SECRET_KEY:         Y0hBTkdFX01FX1RPS0VO      # CHANGE_ME_TOKEN
